Document: prometheus-alertm-settings
Title: Debian prometheus-alertm-settings Manual
Author: <insert document author here>
Abstract: This manual describes what prometheus-alertm-settings is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prometheus-alertm-settings/prometheus-alertm-settings.sgml.gz

Format: postscript
Files: /usr/share/doc/prometheus-alertm-settings/prometheus-alertm-settings.ps.gz

Format: text
Files: /usr/share/doc/prometheus-alertm-settings/prometheus-alertm-settings.text.gz

Format: HTML
Index: /usr/share/doc/prometheus-alertm-settings/html/index.html
Files: /usr/share/doc/prometheus-alertm-settings/html/*.html
