Document: vpn-settings
Title: Debian vpn-settings Manual
Author: <insert document author here>
Abstract: This manual describes what vpn-settings is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vpn-settings/vpn-settings.sgml.gz

Format: postscript
Files: /usr/share/doc/vpn-settings/vpn-settings.ps.gz

Format: text
Files: /usr/share/doc/vpn-settings/vpn-settings.text.gz

Format: HTML
Index: /usr/share/doc/vpn-settings/html/index.html
Files: /usr/share/doc/vpn-settings/html/*.html
