Document: client-conf
Title: Debian client-conf Manual
Author: <insert document author here>
Abstract: This manual describes what client-conf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/client-conf/client-conf.sgml.gz

Format: postscript
Files: /usr/share/doc/client-conf/client-conf.ps.gz

Format: text
Files: /usr/share/doc/client-conf/client-conf.text.gz

Format: HTML
Index: /usr/share/doc/client-conf/html/index.html
Files: /usr/share/doc/client-conf/html/*.html
